name: CMake build (SDK)

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev
      - develop
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "SDK ${{ matrix.config.name }} ${{ matrix.version }}"
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [ "latest", "continuous" ]
        config:
          - {
              name: "Windows",
              os: windows-latest,
              dependencies: "curl -L -O https://github.com/ninja-build/ninja/releases/download/v1.13.1/ninja-win.zip && unzip ninja-win.zip",
              additional_flags: "-GNinja"
            }
          - {
              name: "Ubuntu",
              os: ubuntu-latest,
              dependencies: "sudo apt install -yqq libgl-dev libgl1-mesa-dev libegl1-mesa-dev libdrm-dev libxcomposite-dev libxkbcommon-dev libxkbcommon-x11-dev libwayland-dev libxcb-*-dev libX11-*-dev libz-dev libtinfo6 libxext-dev",
              additional_flags: ""
            }
          - {
              name: "macOS",
              os: macos-latest,
              dependencies: "",
              additional_flags: ""
            }
    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          path: addon

      - name: Install dependencies
        if: matrix.config.dependencies != ''
        shell: bash
        run: |
          ${{ matrix.config.dependencies }}

      - name: Download OSSIA SDK
        uses: ossia/actions/download-ossia-sdk@master
        id: ossia-sdk

      - name: Download Score SDK
        uses: ossia/actions/download-score-sdk@master
        id: score-sdk
        with:
          version: "${{ matrix.version }}"
          extract-path: "${{ runner.temp }}/sdk"

      - name: Build debug
        uses: ossia/actions/build-addon@master
        with:
          addon-path: addon
          build-type: Debug
          score-sdk-path: ${{ steps.score-sdk.outputs.sdk-path }}
          ossia-sdk-path: ${{ steps.ossia-sdk.outputs.sdk-path }}
          additional-flags: ${{ matrix.config.additional_flags }}

      - name: Build release
        uses: ossia/actions/build-addon@master
        with:
          addon-path: addon
          build-type: Release
          score-sdk-path: ${{ steps.score-sdk.outputs.sdk-path }}
          ossia-sdk-path: ${{ steps.ossia-sdk.outputs.sdk-path }}
          additional-flags: ${{ matrix.config.additional_flags }}

      - name: Upload release
        uses: actions/upload-artifact@v4
        with:
          name: plugin-${{ matrix.config.os }}
          path: |
            install/*

  package:
    name: Package
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Package addon
        uses: ossia/actions/package-addon@master

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: deploy