name: JIT

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - dev
      - develop
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  jit:
    name: "JIT ${{ matrix.config.name }} ${{ matrix.version }}"
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version: [ "latest", "continuous" ]
        config:
          - { name: "Windows", os: windows-latest }
          - { name: "Ubuntu", os: ubuntu-latest }
          - { name: "macOS", os: macos-latest }

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Download Score SDK
        uses: ossia/actions/download-score-sdk@master
        with:
          version: "${{ matrix.version }}"
          extract-path: "${{ runner.temp }}/sdk"

      - name: JIT compile test
        uses: ossia/actions/jit-compile@master
        with:
          score-version: ${{ matrix.version }}
          sdk-path: "${{ runner.temp }}/sdk/usr"
